import Head from 'next/head'
import { FC, ReactNode } from 'react'

import { Header } from './Header'
import { Footer } from './Footer'
import { Box, createStyles } from '@mantine/core'
import { Content } from './Content'

interface Props {
  title: string
  children: ReactNode
}

const useStyles = createStyles({
  container: {
    position: 'relative',
    minHeight: '100vh'
  },
  wrapper: {
    paddingBottom: 180
  }
})

export const Layout: FC<Props> = ({ children, title }) => {
  const { classes } = useStyles()

  return (
    <>
      <Head>
        <title>{title} - GSV Eintracht Gailenkirchen</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box className={classes.container}>
        <Box className={classes.wrapper}>
          <Header></Header>
          <Content>{children}</Content>
        </Box>
        <Footer></Footer>
      </Box>
    </>
  )
}
