import Head from 'next/head'
import { FC, ReactNode } from 'react'

import { Header } from './Header'
import { Footer } from './Footer'

interface Props {
  title: string
  children: ReactNode
}

export const Layout: FC<Props> = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title} - GSV Eintracht Gailenkirchen</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header></Header>
      <main>{children}</main>
      <Footer></Footer>
    </>
  )
}
